### PR TITLE
Fix error with latest WebProfilerServiceProvider

### PR DESCRIPTION
**Pull request by arduanov**
Fix Cannot override frozen service "data_collector.templates"

### CODE REVIEW

**Comment by chanmix51** [comment]
Seems good to me :+1: 

@sanpii ?

**Comment by sanpii** [comment]
Your patch fixes the error message but the template isn’t overloaded.

**Comment by arduanov** [comment]
array_merge made same thing, simply add db template to data_collector.templates
Where template must be overloaded?

```
        $app['data_collector.templates'] = $app->extend('data_collector.templates', function ($templates) {
            return array_merge(
                $templates,
                [['db', '@Pomm/Profiler/db.html.twig']]
            );
        });
```

**Comment by sanpii** [comment]
> Where template must be overloaded?

I have said nothing: I confused with the timeline template. It’s ok :+1:

**Pull request merged**
